# see setup-dev-db.sh
version: '3'
services:
  xxx_service:
    build:
      context: .
    container_name: xxx-service
    ports:
    - 2329:2329
    environment:
      - POSTGRES_DB=$DATABASE_NAME
      - POSTGRES_PASSWORD=$POSTGRESQL_PASSWORD
      - POSTGRES_USER=$POSTGRESQL_USER
      - POSTGRES_PASSWORD=$POSTGRESQL_PORT
      - POSTGRES_PASSWORD=$POSTGRESQL_HOST
  xxx_service_flyway:
    build:
      context: ./docker/flyway
    container_name: xxx_service_flyway
    volumes:
      - ./flyway/database-migrations:/flyway/sql
    # make sure postgres is up and running before executing command
    entrypoint: ["bash", "/flyway/bin/wait-for-postgres.sh", "xxx_service_postgres", postgres, "--", "flyway"]
    command:
      # note:
      # 1) we can use either host.docker.internal or xxx_service_postgres
      # 2) localhost is internal to container only, to still wanting to talk to another container, use
      # network_mode: host
      -url=jdbc:postgresql://xxx_service_postgres:${POSTGRESQL_PORT}/${DATABASE_NAME} -user=postgres -password=postgres migrate
    depends_on:
      - xxx_service_postgres
  xxx_service_postgres:
    container_name: xxx_service_postgres
    build:
      context: ./docker/postgres
    # image: gitlab.yyy.org/docker/dependency_proxy/containers/postgres:10
    environment:
      - POSTGRES_DB=$DATABASE_NAME
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      # to allow connections from other hosts via password set $POSTGRESQL_HOST_AUTH_METHOD
      # which does echo "host all all all $POSTGRESQL_HOST_AUTH_METHOD" >> pg_hba.conf
      # see https://hub.docker.com/_/postgres for more info
      - POSTGRES_HOST_AUTH_METHOD=password
    # wait for postgres to be fully ready
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - $POSTGRESQL_PORT:$POSTGRESQL_PORT
    volumes:
      # note: for customizing pg_hba.conf and postgresql.conf see
      #  https://github.com/osssanitizer/osspolice/blob/master/postgresql/docker-compose.yml
      #  volumes:
      #      - ./postgresql.conf:/etc/postgresql/postgresql.conf
      #      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ./pgdata:/var/lib/postgresql/data
